### ISSUE TITLE
サンプルコード実行エラー

### ISSUE THREAD

**Issue by amrocs** [8th713/LearnAngularJS#3]
「すぐできる AngularJS」の「新しい ToDo を作成し表示できるようにする」において
ソースのタブ選択でapp.jsを選択すると、1行目に

　angular.module('App', ['LocationBar'])

と書かれていますが、
['LocationBar']ではなく[]が正しいのではないでしょうか？
とりあえずコピペして実行して動きを見てみようと思ったんですが、エラーで動きません。
色々調べて実験してみるうち、上記の修正をすると動くようになりました。
後で気づきましたが説明文では[]となっています。

**Comment by amrocs** [comment]
他のページのソースも同じになっているようです。
Chrome40ですが動きませんでした。

**Comment by 8th713** [comment]
[モックアップを作成する](http://8th713.github.io/LearnAngularJS/#/todo/step02) の最後の Tip にある通り
 `LocationBar` はプレビュー部分でアドレスバー的なものを表示するためのモジュールです。
なので写経などをするときは仰るとおり `[]` にするのが正しいです。

**Comment by 8th713** [comment]
注意書するページと初めて `LocationBar` を使用しているページが違うのでややこしいですね。
申し訳ないです。
