### ISSUE TITLE
'input 要素を選択状態にする'のところで選択状態にならない

### ISSUE THREAD

**Issue by ghost** [8th713/LearnAngularJS#6]
手順と関係ないところで恐縮なのですが、Angular v1.3.0以降のバージョンを使用するとアイテムを編集状態にしたときにテキストが選択状態になりません。手順どおりv1.2.0rc3を使用するとちゃんと選択状態になります。
バージョンアップによって何か変更されているのでしょうか？もしお心当たりあれば教えて下さい。

めっちゃためになるサイトありがとうございます！

**Comment by 8th713** [comment]
v1.3.0 あたりで $animate との兼ね合いで ngShow の挙動やタイミングに調整が入ったようなのでその影響ではないかと思われます。
$watch 自体は動いているようなので slect メソッドの実行を遅延させる方法で回避するのがいいんじゃないでしょうか？

``` js
scope.$watch(attrs.mySelect, function (val) {
  if (val) {
    setTimeput(function () {
      $el[0].select();
    }, 0);
  }
});
```

> めっちゃためになるサイトありがとうございます！

もう既に結構古い情報になってしまったのであんまり参考にならないかもです。

**Comment by ghost** [comment]
確かに、遅延させると選択されますね。ngShowあたりよく調べてみます。ありがとうございます！
